/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import classes.Teacher;
import util.TeacherTitleException;

import javax.swing.*;

/**
 *
 * @author CHester
 */
public class AddTeacherJDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddTeacherJDialog
     */
    public AddTeacherJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTeacherJPanel1 = new frame.AddTeacherJPanel();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addButton.setText("添加");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    addButtonActionPerformed(evt);
                } catch (TeacherTitleException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addTeacherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addTeacherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) throws TeacherTitleException {//GEN-FIRST:event_addButtonActionPerformed
        String number, sex, birthday, id, department, teacherNumber, title, timeInJob;
        if (addTeacherJPanel1.idTextField.getText().length() != 18) {
            JOptionPane.showMessageDialog(null, "身份证长度必须为18位!");
            return;
        }
        //TODO:此处请仿照上面添加输入的合法性检查!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        if (!addTeacherJPanel1.maleRadioButton.isSelected()) {
            if (addTeacherJPanel1.femaleRadioButton.isSelected()) {
                sex = addTeacherJPanel1.femaleRadioButton.getText().trim();
            } else {
                JOptionPane.showMessageDialog(null, "请选择性别!");
                return;
            }
        } else {
            sex = addTeacherJPanel1.maleRadioButton.getText().trim();
        }

        //抛出教师职称异常
        if (!addTeacherJPanel1.titleTextField.getText().trim().equals("讲师")) {
            if (!addTeacherJPanel1.titleTextField.getText().trim().equals("副教授")) {
                if (!addTeacherJPanel1.titleTextField.getText().trim().equals("教授")) {
                    throw new TeacherTitleException("教师职称只能为讲师、副教授或教授。");
                }
            }
        }


        number = this.addTeacherJPanel1.numberTextField.getText().trim();
        birthday = this.addTeacherJPanel1.birthdayTextField.getText().trim();
        id = this.addTeacherJPanel1.idTextField.getText().trim();
        department = this.addTeacherJPanel1.departmentTextField.getText().trim();
        teacherNumber = this.addTeacherJPanel1.teacherNumberTextField.getText().trim();
        title = this.addTeacherJPanel1.titleTextField.getText().trim();
        timeInJob = this.addTeacherJPanel1.timeInJobTextField.getText().trim();
        teacher = new Teacher(number, sex, birthday, id, department, teacherNumber, title, timeInJob);
        this.dispose();
        return;
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTeacherJDialog dialog = new AddTeacherJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private frame.AddTeacherJPanel addTeacherJPanel1;
    // End of variables declaration//GEN-END:variables
    private Teacher teacher;

    public Teacher getTeacher() {
        return teacher;
    }
}
