/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import classes.People;
import classes.Student;
import classes.Teacher;
import configuration.Conf;
import classes.PeopleLinkedListCollection;
import dao.Dao;

import javax.swing.*;
import java.util.Iterator;

/**
 * 展示全体人员信息窗口
 * @author CHester
 */
public class DisplayInfoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DisplayInfoJFrame
     */
    public DisplayInfoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NextInfoButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        displayInfoJPanel = new frame.DisplayInfoJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NextInfoButton.setText("下一个");
        NextInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextInfoButtonActionPerformed(evt);
            }
        });

        ReturnButton.setText("返回");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        displayInfoJPanel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextInfoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReturnButton)
                                .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(displayInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(displayInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NextInfoButton)
                                        .addComponent(ReturnButton))
                                .addContainerGap())
        );


        path = Conf.getPath();
        peopleLinkedListCollection = new PeopleLinkedListCollection();
        peopleLinkedListCollection.peopleLinkedList = Dao.readFromStorage(path);
        iterator = peopleLinkedListCollection.peopleLinkedList.iterator();
        this.nextInfo();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextInfoButtonActionPerformed
        // TODO add your handling code here:
        this.nextInfo();
    }//GEN-LAST:event_NextInfoButtonActionPerformed

    private void ReturnButtonActionPerformed (java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayInfoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextInfoButton;
    private javax.swing.JButton ReturnButton;
    private frame.DisplayInfoJPanel displayInfoJPanel;

    // End of variables declaration//GEN-END:variables

    private PeopleLinkedListCollection peopleLinkedListCollection;
    private Iterator<People> iterator;
    private String path;

    /**
     * 读取下一名人员的信息,根据该人员是教师或者学生进行相应格式的展示
     */
    public void nextInfo() {
        if (!iterator.hasNext()) {
            JOptionPane.showMessageDialog(null, "已到最后一条!");
            return;
        }
        People p = iterator.next();
        this.displayInfoJPanel.jLabel1.setText("编号:");
        this.displayInfoJPanel.jLabel2.setText("性别:");
        this.displayInfoJPanel.jLabel3.setText("生日:");
        this.displayInfoJPanel.jLabel4.setText("身份证号:");
        this.displayInfoJPanel.infoJLabel1.setText(p.getNumber());
        this.displayInfoJPanel.infoJLabel2.setText(p.getSex().toString());
        this.displayInfoJPanel.infoJLabel3.setText(p.getBirthday());
        this.displayInfoJPanel.infoJLabel4.setText(p.getId());
        if (p instanceof Student) {
            this.displayInfoJPanel.jLabel5.setText("学号:");
            this.displayInfoJPanel.jLabel6.setText("专业:");
            this.displayInfoJPanel.jLabel7.setText("年级:");
            this.displayInfoJPanel.jLabel8.setVisible(false);
            this.displayInfoJPanel.infoJLabel8.setVisible(false);
            this.displayInfoJPanel.infoJLabel5.setText(((Student) p).getStudentNumber());
            this.displayInfoJPanel.infoJLabel6.setText(((Student) p).getDiscipline());
            this.displayInfoJPanel.infoJLabel7.setText(((Student) p).getGrade());
        } else if (p instanceof Teacher) {
            this.displayInfoJPanel.jLabel5.setText("院系:");
            this.displayInfoJPanel.jLabel6.setText("工号:");
            this.displayInfoJPanel.jLabel7.setText("职称:");
            this.displayInfoJPanel.jLabel8.setVisible(true);
            this.displayInfoJPanel.infoJLabel8.setVisible(true);
            this.displayInfoJPanel.jLabel8.setText("任职时长:");
            this.displayInfoJPanel.infoJLabel5.setText(((Teacher) p).getDepartment());
            this.displayInfoJPanel.infoJLabel6.setText(((Teacher) p).getTeacherNumber());
            this.displayInfoJPanel.infoJLabel7.setText(((Teacher) p).getTitle());
            this.displayInfoJPanel.infoJLabel8.setText(((Teacher) p).getTimeInJob());
        }
    }
}
