/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import classes.People;
import classes.PeopleLinkedListCollection;
import classes.Student;
import classes.Teacher;
import dao.Dao;

import javax.swing.*;
import java.awt.*;
import java.util.Iterator;

/**
 *
 * @author CHester
 */
public class DisplayInfoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DisPlayInfoJDialog
     */
    public DisplayInfoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DisplayInfoJDialog(Frame owner, boolean modal, PeopleLinkedListCollection peopleLinkedListCollection) {
        super(owner, modal);
        initComponents();
        this.peopleLinkedListCollection = peopleLinkedListCollection;
        iterator = this.peopleLinkedListCollection.peopleLinkedList.iterator();
        this.nextInfo();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayInfoJPanel1 = new frame.DisplayInfoJPanel();
        nextJButton = new javax.swing.JButton();
        returnJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nextJButton.setText("下一个");
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });

        returnJButton.setText("返回");
        returnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(displayInfoJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(nextJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayInfoJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextJButton)
                    .addComponent(returnJButton))
                .addGap(0, 71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed
        this.nextInfo();
    }//GEN-LAST:event_nextJButtonActionPerformed

    private void returnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayInfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DisplayInfoJDialog dialog = new DisplayInfoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frame.DisplayInfoJPanel displayInfoJPanel1;
    private javax.swing.JButton nextJButton;
    private javax.swing.JButton returnJButton;
    // End of variables declaration//GEN-END:variables
    private PeopleLinkedListCollection peopleLinkedListCollection;
    private Iterator<People> iterator;

    /**
     * 读取下一名人员的信息,根据该人员是教师或者学生进行相应格式的展示
     */
    public void nextInfo() {
        if (!iterator.hasNext()) {
            JOptionPane.showMessageDialog(null, "已到最后一条!");
            return;
        }
        People p = iterator.next();
        this.displayInfoJPanel1.jLabel1.setText("编号:");
        this.displayInfoJPanel1.jLabel2.setText("性别:");
        this.displayInfoJPanel1.jLabel3.setText("生日:");
        this.displayInfoJPanel1.jLabel4.setText("身份证号:");
        this.displayInfoJPanel1.infoJLabel1.setText(p.getNumber());
        this.displayInfoJPanel1.infoJLabel2.setText(p.getSex().toString());
        this.displayInfoJPanel1.infoJLabel3.setText(p.getBirthday());
        this.displayInfoJPanel1.infoJLabel4.setText(p.getId());
        if (p instanceof Student) {
            this.displayInfoJPanel1.jLabel8.setVisible(false);
            this.displayInfoJPanel1.infoJLabel8.setVisible(false);
            this.displayInfoJPanel1.jLabel5.setText("学号:");
            this.displayInfoJPanel1.jLabel6.setText("专业:");
            this.displayInfoJPanel1.jLabel7.setText("年级:");
            this.displayInfoJPanel1.infoJLabel5.setText(((Student) p).getStudentNumber());
            this.displayInfoJPanel1.infoJLabel6.setText(((Student) p).getDiscipline());
            this.displayInfoJPanel1.infoJLabel7.setText(((Student) p).getGrade());
        } else if (p instanceof Teacher) {
            this.displayInfoJPanel1.jLabel8.setVisible(true);
            this.displayInfoJPanel1.infoJLabel8.setVisible(true);
            this.displayInfoJPanel1.jLabel5.setText("院系:");
            this.displayInfoJPanel1.jLabel6.setText("工号:");
            this.displayInfoJPanel1.jLabel7.setText("职称:");
            this.displayInfoJPanel1.jLabel8.setText("任职时长:");
            this.displayInfoJPanel1.infoJLabel5.setText(((Teacher) p).getDepartment());
            this.displayInfoJPanel1.infoJLabel6.setText(((Teacher) p).getTeacherNumber());
            this.displayInfoJPanel1.infoJLabel7.setText(((Teacher) p).getTitle());
            this.displayInfoJPanel1.infoJLabel8.setText(((Teacher) p).getTimeInJob());
        }
    }
}
